# -*- coding: utf-8 -*-
"""fraud model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11H1CHIAo5HTqa_lJA9YCcbc3ULz9zCsf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import os 
file_path = r"C:\Users\lenovo\OneDrive\المستندات\GitHub\Audit-Assistant\Notebooks\fraud_dataset_30pct.xlsx"


if os.path.exists(file_path):
    df = pd.read_excel(file_path)
    print("File loaded successfully!")
else:
    print("File not found. Check the path!")
df = pd.read_excel(file_path)


df.head()
df.info()
print(df.shape)

df.head(5)

def plotCorrelationMatrix(df, graphWidth):

    df = df.dropna(axis=1)
    df = df.select_dtypes(include=[np.number]) # Select only numeric columns
    df = df[[col for col in df if df[col].nunique() > 1]]
    if df.shape[1] < 2:
        print(f'No correlation plots shown: The number of non-NaN or constant columns ({df.shape[1]}) is less than 2')
        return
    corr = df.corr()
    plt.figure(num=None, figsize=(graphWidth, graphWidth), dpi=80, facecolor='w', edgecolor='k')
    corrMat = plt.matshow(corr)
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    plt.gca().xaxis.tick_bottom()
    plt.colorbar(corrMat)
    plt.title('Correlation Matrix', fontsize=15)
    plt.show()

def plotScatterMatrix(df, plotSize, textSize):
    df = df.select_dtypes(include =[np.number])
    df = df.dropna('columns')
    df = df[[col for col in df if df[col].nunique() > 1]]
    columnNames = list(df)
    if len(columnNames) > 10:
        columnNames = columnNames[:10]
    df = df[columnNames]
    ax = pd.plotting.scatter_matrix(df, alpha=0.75, figsize=[plotSize, plotSize], diagonal='kde')
    corrs = df.corr().values
    for i, j in zip(*plt.np.triu_indices_from(ax, k = 1)):
        ax[i, j].annotate('Corr. coef = %.3f' % corrs[i, j], (0.8, 0.2), xycoords='axes fraction', ha='center', va='center', size=textSize)
    plt.suptitle('Scatter and Density Plot')
    plt.show()

plotCorrelationMatrix(df, 8)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

# Assuming 'is_suspicious' is the target variable
X = df.drop("is_suspicious", axis=1)
y = df["is_suspicious"]

# Drop non-numeric columns that are not suitable for StandardScaler
non_numeric_cols = ['user_id', 'transaction_date', 'transaction_time', 'time_suffix',
                    'destination_account', 'source_account', 'branch', 'currency',
                    'device', 'ip', 'location']
X = X.drop(columns=[col for col in non_numeric_cols if col in X.columns])


if y.dtypes == "object":
    y = LabelEncoder().fit_transform(y)

# No need to concatenate and dropna on 'is_suspicious' again if y is already the target column


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

input_dim = X_train.shape[1]
encoding_dim = 16

input_layer = Input(shape=(input_dim,))
encoder = Dense(32, activation="relu")(input_layer)
encoder = Dense(encoding_dim, activation="relu")(encoder)

decoder = Dense(32, activation="relu")(encoder)
decoder = Dense(input_dim, activation="sigmoid")(decoder)

autoencoder = Model(inputs=input_layer, outputs=decoder)
autoencoder.compile(optimizer="adam", loss="mse")

X_train_nonfraud = X_train[y_train == 0]  # فقط العمليات الطبيعية
autoencoder.fit(
    X_train_nonfraud, X_train_nonfraud,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)


reconstructions = autoencoder.predict(X_test)
mse = np.mean(np.power(X_test - reconstructions, 2), axis=1)


threshold = np.percentile(mse, 95)  # أعلى 5% نعتبرها Fraud
print(f"Threshold: {threshold}")


y_pred = (mse > threshold).astype(int)

print("\n Classification Report:")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Not Fraud", "Fraud"],
            yticklabels=["Not Fraud", "Fraud"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Autoencoder")
plt.show()

import os
import random
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.metrics import (roc_auc_score, precision_recall_curve, average_precision_score,
                             precision_score, recall_score, f1_score, confusion_matrix)
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM
import xgboost as xgb
from imblearn.over_sampling import SMOTE
import joblib
import matplotlib.pyplot as plt

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)

def evaluate_binary(y_true, y_scores, threshold=None, top_k=None):
    result = {}
    try:
        result['roc_auc'] = roc_auc_score(y_true, y_scores)
    except Exception:
        result['roc_auc'] = None
    result['avg_precision'] = average_precision_score(y_true, y_scores)

    if threshold is not None:
        y_pred = (y_scores >= threshold).astype(int)
    elif top_k is not None:
        k = int(top_k)
        idx = np.argsort(y_scores)[-k:]
        y_pred = np.zeros_like(y_true)
        y_pred[idx] = 1
    else:
        y_pred = (y_scores >= 0.5).astype(int)

    result['precision'] = precision_score(y_true, y_pred, zero_division=0)
    result['recall'] = recall_score(y_true, y_pred, zero_division=0)
    result['f1'] = f1_score(y_true, y_pred, zero_division=0)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    result['confusion'] = {'tn': int(tn), 'fp': int(fp), 'fn': int(fn), 'tp': int(tp)}
    return result


def plot_precision_recall(y_true, y_scores, title='Precision-Recall'):
    precision, recall, _ = precision_recall_curve(y_true, y_scores)
    ap = average_precision_score(y_true, y_scores)
    plt.figure(figsize=(6,4))
    plt.plot(recall, precision)
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.title(f"{title} — AP={ap:.4f}")
    plt.grid(True)
    plt.show()

import seaborn as sns
plt.figure(figsize=(6,6))
colors = ['#66b3ff','#ff6666']
df['is_suspicious'].value_counts().plot.pie(autopct='%1.1f%%', colors=colors, startangle=90)
plt.title('Distribution of Normal vs Fraud Transactions')
plt.ylabel('')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x='is_suspicious', data=df, palette=['#66b3ff','#ff6666'])
plt.title('Count of Normal vs Fraud Transactions')
plt.show()

plt.figure(figsize=(10,6))
sns.boxplot(x='is_suspicious', y='amount', data=df, palette=['#66b3ff','#ff6666'])
plt.yscale('log')
plt.title('Transaction Amounts by Class (log scale)')
plt.show()

FEATURE_COLS = [c for c in df.columns if c not in ['is_suspicious']]
TARGET = 'is_suspicious'

X = df[FEATURE_COLS].copy()
y = df[TARGET].copy()

# Select only numeric columns for scaling
numeric_cols = ['amount', 'old_balance', 'new_balance']
scaler_amt = RobustScaler()

for col in numeric_cols:
    if col in X.columns:
        X[f'{col}_scaled'] = scaler_amt.fit_transform(X[[col]])
        X.drop(columns=[col], inplace=True)


X.head()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE)

print('Train shape:', X_train.shape, 'Test shape:', X_test.shape)
print('Train class dist:\n', y_train.value_counts(normalize=True))

iso = IsolationForest(n_estimators=200, max_samples='auto', contamination='auto', random_state=RANDOM_STATE)
iso.fit(X_train)

iso_scores = -iso.decision_function(X_test)
res_iso = evaluate_binary(y_test.values, iso_scores)
print('Isolation Forest results:', res_iso)
plot_precision_recall(y_test.values, iso_scores, title='Isolation Forest')

lof = LocalOutlierFactor(n_neighbors=20, contamination='auto', novelty=True)

# Drop non-numeric columns before fitting the model
non_numeric_cols = ['user_id', 'transaction_date', 'transaction_time', 'time_suffix',
                    'destination_account', 'source_account', 'branch', 'currency',
                    'device', 'ip', 'location']
X_train_numeric = X_train.drop(columns=[col for col in non_numeric_cols if col in X_train.columns])
X_test_numeric = X_test.drop(columns=[col for col in non_numeric_cols if col in X_test.columns])

lof.fit(X_train_numeric)
lof_scores = -lof.decision_function(X_test_numeric)
res_lof = evaluate_binary(y_test.values, lof_scores)
print('LOF results:', res_lof)
plot_precision_recall(y_test.values, lof_scores, title='Local Outlier Factor')

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
scale_pos_weight = neg / pos
print('scale_pos_weight:', scale_pos_weight)

# Drop non-numeric columns before creating DMatrix
non_numeric_cols = ['user_id', 'transaction_date', 'transaction_time', 'time_suffix',
                    'destination_account', 'source_account', 'branch', 'currency',
                    'device', 'ip', 'location']
X_train_numeric = X_train.drop(columns=[col for col in non_numeric_cols if col in X_train.columns])
X_test_numeric = X_test.drop(columns=[col for col in non_numeric_cols if col in X_test.columns])


dtrain = xgb.DMatrix(X_train_numeric, label=y_train)
dtest = xgb.DMatrix(X_test_numeric, label=y_test)
params = {
    'objective':'binary:logistic',
    'eval_metric':'aucpr',
    'tree_method':'hist',
    'learning_rate':0.05,
    'max_depth':6,
    'scale_pos_weight': scale_pos_weight,
    'seed': RANDOM_STATE
}

model_xgb = xgb.train(params, dtrain, num_boost_round=300, evals=[(dtrain, 'train')], verbose_eval=False)

xgb_scores = model_xgb.predict(dtest)
res_xgb = evaluate_binary(y_test.values, xgb_scores)
print('XGBoost (weighted) results:', res_xgb)
plot_precision_recall(y_test.values, xgb_scores, title='XGBoost (weighted)')

sm = SMOTE(random_state=RANDOM_STATE)

# Drop non-numeric columns before applying SMOTE and fitting the model
non_numeric_cols = ['user_id', 'transaction_date', 'transaction_time', 'time_suffix',
                    'destination_account', 'source_account', 'branch', 'currency',
                    'device', 'ip', 'location']
X_train_numeric = X_train.drop(columns=[col for col in non_numeric_cols if col in X_train.columns])
X_test_numeric = X_test.drop(columns=[col for col in non_numeric_cols if col in X_test.columns])

X_res, y_res = sm.fit_resample(X_train_numeric, y_train)
print('Resampled train shape:', X_res.shape, y_res.value_counts())

from xgboost import XGBClassifier
xgb_sm = XGBClassifier(n_estimators=200, learning_rate=0.05, use_label_encoder=False, eval_metric='logloss',
                       max_depth=6, random_state=RANDOM_STATE)
xgb_sm.fit(X_res, y_res)

xgb_sm_scores = xgb_sm.predict_proba(X_test_numeric)[:,1]
res_xgb_sm = evaluate_binary(y_test.values, xgb_sm_scores)
print('XGBoost + SMOTE results:', res_xgb_sm)
plot_precision_recall(y_test.values, xgb_sm_scores, title='XGBoost + SMOTE')

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, BatchNormalization
from tensorflow.keras.optimizers import Adam

# Drop non-numeric columns before scaling
non_numeric_cols = ['user_id', 'transaction_date', 'transaction_time', 'time_suffix',
                    'destination_account', 'source_account', 'branch', 'currency',
                    'device', 'ip', 'location']

X_train_normal = X_train[y_train==0].drop(columns=[col for col in non_numeric_cols if col in X_train.columns])
X_val = X_test.drop(columns=[col for col in non_numeric_cols if col in X_test.columns])

scaler = StandardScaler()
X_train_norm = scaler.fit_transform(X_train_normal)
X_val_scaled = scaler.transform(X_val)

X_train_norm = np.nan_to_num(X_train_norm).astype(np.float32)
X_val_scaled = np.nan_to_num(X_val_scaled).astype(np.float32)

input_dim = X_train_norm.shape[1]
encoding_dim = max(8, input_dim // 4)

inp = Input(shape=(input_dim,))
encoded = Dense(encoding_dim, activation='relu')(inp)
encoded = BatchNormalization()(encoded)
encoded = Dense(encoding_dim//2, activation='relu')(encoded)
encoded = BatchNormalization()(encoded)
decoded = Dense(encoding_dim//2, activation='relu')(encoded)
decoded = Dense(encoding_dim, activation='relu')(decoded)
decoded = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inp, decoded)
autoencoder.compile(optimizer=Adam(learning_rate=1e-3), loss='mse')

history = autoencoder.fit(
    X_train_norm, X_train_norm,
    epochs=10,
    batch_size=64,
    shuffle=True,
    validation_data=(X_val_scaled, X_val_scaled),
    verbose=1
)

reconstructions = autoencoder.predict(X_val_scaled)
mse = np.mean(np.square(reconstructions - X_val_scaled), axis=1)

res_ae = evaluate_binary(y_test.values, mse)
print('Autoencoder results:', res_ae)
plot_precision_recall(y_test.values, mse, title='Autoencoder')

results = [
    {'model':'IsolationForest', **res_iso},
    {'model':'LOF', **res_lof},
    {'model':'XGBoost_weighted', **res_xgb},
    {'model':'XGBoost_SMOTE', **res_xgb_sm},
    {'model':'Autoencoder', **res_ae},
]
pd.DataFrame(results)

import seaborn as sns

# Collect main metrics
df_results = pd.DataFrame([
    {'model':'IsolationForest', **res_iso},
    {'model':'LOF', **res_lof},
    {'model':'XGBoost_weighted', **res_xgb},
    {'model':'XGBoost_SMOTE', **res_xgb_sm},
    {'model':'Autoencoder', **res_ae},
])

# Show metrics table
display(df_results[['model','roc_auc','avg_precision','precision','recall','f1']])

metrics_to_plot = ['f1','precision','recall']
df_melt = df_results.melt(id_vars='model', value_vars=metrics_to_plot, var_name='metric', value_name='score')

plt.figure(figsize=(8,5))
sns.barplot(data=df_melt, x='model', y='score', hue='metric')
plt.title("Model Performance Comparison")
plt.xticks(rotation=30)
plt.ylim(0,1)
plt.show()


from sklearn.metrics import ConfusionMatrixDisplay

y_pred_best = (xgb_sm_scores >= 0.5).astype(int)
cm = confusion_matrix(y_test, y_pred_best)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Normal','Fraud'])
disp.plot(cmap="Blues", values_format='d')
plt.title("Confusion Matrix — XGBoost + SMOTE")
plt.show()

from sklearn.metrics import roc_curve, auc

def plot_roc_pr(y_true, y_scores, model_name="Model"):
    fpr, tpr, _ = roc_curve(y_true, y_scores)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(6,4))
    plt.plot(fpr, tpr, label=f'ROC curve (AUC={roc_auc:.3f})')
    plt.plot([0,1],[0,1],'--', color='gray')
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(f"ROC Curve — {model_name}")
    plt.legend()
    plt.grid(True)
    plt.show()

    plot_precision_recall(y_true, y_scores, title=f"Precision-Recall — {model_name}")

# Run for XGBoost weighted
plot_roc_pr(y_test.values, xgb_scores, model_name="XGBoost Weighted")

example_idx = X_test.sample(5, random_state=RANDOM_STATE).index
example_data = X_test.loc[example_idx]

# Drop non-numeric columns before making predictions
non_numeric_cols = ['user_id', 'transaction_date', 'transaction_time', 'time_suffix',
                    'destination_account', 'source_account', 'branch', 'currency',
                    'device', 'ip', 'location']
example_data_numeric = example_data.drop(columns=[col for col in non_numeric_cols if col in example_data.columns])

example_scores = xgb_sm.predict_proba(example_data_numeric)[:,1]
for idx, score in zip(example_idx, example_scores):
    label = "FRAUD " if score>0.5 else "Normal "
    print(f"TransactionID: {idx} | Score: {score:.4f} | {label}")

